#!/usr/bin/env python3
"""Generate the frozen conformance vectors (format §11) into vectors/ and the
built-in self-test data (a minimal copy of them) into src/apcaw/data/selftest.json.

    .venv/bin/python tools/make_vectors.py [--no-mp3]

Deterministic: rerunning reproduces every file byte for byte (the MP3 round trip only with the
same ffmpeg / LAME build, which MANIFEST.json records). Needs ffmpeg unless --no-mp3.
"""
import sys

sys.dont_write_bytecode = True

import argparse
import hashlib
import json
import math
import pathlib
import platform
import shutil
import subprocess
import tempfile

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import apcaw                                                 # noqa: E402
from apcaw import NB, WB, Options, keygen, sign, verify      # noqa: E402
from apcaw import cli, selftest                              # noqa: E402
from apcaw.embed import build_stream                         # noqa: E402
from apcaw.io import quantize_pcm16, read_audio, write_pcm16  # noqa: E402
from apcaw.layout import capacity, mag_pairs, mt19937_outputs, phase_bins, replicas, seed_from_pk  # noqa: E402
from apcaw.payload import build_payload, rs_decode           # noqa: E402
from apcaw.verify import read_soft                           # noqa: E402

VECTORS = ROOT / "vectors"
SELFTEST_JSON = ROOT / "src" / "apcaw" / "data" / "selftest.json"
CLIP_ID = "8555-284447-0010"
CLIP_SRC = ROOT / "tests" / "media" / f"0001_librispeech_{CLIP_ID}.wav"
LOCAL_TMP = ROOT / ".tmp"

SR = 44100
SECRET = bytes(range(32))
OTHER_SECRET = bytes(range(1, 33))
NIPS_MSG = "NIPS2026: Authenticity Token for Deepfake Defense"
LONG_MSG = ("apcaw-v1 conformance: the longest message, 159 bytes, fills one RS(255,225) "
            "block exactly. " * 2)[:159]
LAYOUT_SEEDS = [0, 1, 42, 4294967295]
RS_SEEDS = [1, 2, 3, 4, 5]
RS_ERRORS = [5, 15, 16]


def dump(path: pathlib.Path, obj) -> None:
    path.write_text(json.dumps(obj, indent=1) + "\n")
    print(f"wrote {path.relative_to(ROOT)}")


def floats17(v) -> str:
    """JSON array of float64 values with 17 significant digits (exact round trip)."""
    assert all(math.isfinite(a) for a in v)
    return "[" + ",".join(format(float(a), ".17g") for a in v) + "]"


def bits_str(bits: np.ndarray) -> str:
    return "".join("1" if b else "0" for b in bits)


def ffmpeg_version() -> str | None:
    if shutil.which("ffmpeg") is None:
        return None
    out = subprocess.run(["ffmpeg", "-version"], capture_output=True, text=True).stdout
    return out.splitlines()[0] if out else None


def mp3_roundtrip(wav: pathlib.Path, out: pathlib.Path, n: int) -> None:
    """PCM16 WAV -> ffmpeg -b:a 128k MP3 -> 44.1 kHz mono PCM16, padded / trimmed to n samples
    (the benchmark's convention)."""
    with tempfile.TemporaryDirectory(dir=LOCAL_TMP) as td:
        td = pathlib.Path(td)
        subprocess.run(["ffmpeg", "-y", "-i", str(wav), "-b:a", "128k", str(td / "mid.mp3")],
                       check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        subprocess.run(["ffmpeg", "-y", "-i", str(td / "mid.mp3"), "-ar", str(SR), "-ac", "1",
                        "-c:a", "pcm_s16le", str(td / "out.wav")],
                       check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        d, sr = read_audio(td / "out.wav")
    assert sr == SR
    d = np.pad(d, (0, max(0, n - len(d))))[:n]
    write_pcm16(out, np.round(d * 32768.0).astype(np.int16), SR)


def cli_sign(inp: pathlib.Path, out: pathlib.Path, legacy: bool) -> None:
    """`apcaw sign` with the fixed secret key (closed loop: exit 0 only if the file verifies)."""
    with tempfile.TemporaryDirectory(dir=LOCAL_TMP) as td:
        key = pathlib.Path(td) / "sk.bin"
        key.write_bytes(SECRET)
        argv = ["sign", "-i", str(inp), "-o", str(out), "-k", str(key), "-m", NIPS_MSG,
                "--profile", "wb"] + (["--legacy"] if legacy else [])
        rc = cli.main(argv)
    if rc != 0:
        raise SystemExit(f"apcaw sign exited {rc} for {out.name}")


def result_fields(r) -> dict:
    return {"verified": r.verified, "message_hex": r.message.hex() if r.message is not None else None,
            "channel": r.channel, "profile": r.profile, "path": r.path,
            "rs_corrected": r.rs_corrected, "payload_bits": r.payload_bits,
            "candidates_tried": r.candidates_tried, "rs_passes": r.rs_passes,
            "sig_checks": r.sig_checks, "reason": r.reason}


README = f"""\
# apcaw-v1 conformance vectors

Generated by the Python reference (`tools/make_vectors.py`) and frozen. §11 of the format
(the paper, Appendix A) states what an implementation must match. `MANIFEST.json` holds
the SHA-256 of every file and the library / ffmpeg versions used.

Keys: the secret key is the raw Ed25519 seed `00 01 02 .. 1f` (`secret_seed_hex`); the
wrong-key negative uses the seed `01 02 .. 20`. `key_seed` is the layout seed of the signing key.

| file | content |
|---|---|
| `layout.json` | `Kp` (`phase_bins`) and `pairs[perm]` (`mag_pairs`) for seeds 0, 1, 42, 2^32-1 and the key seed, profiles wb and nb |
| `mt19937.json` | first 16 raw uint32 outputs of MT19937 `init_genrand(seed)` (= `numpy.random.RandomState(seed)`) for the same seeds |
| `payload.json` | messages "", "A", the paper message and a 159-byte message: signature `S`, payload `C` (RS codeword), header bits, and the wb stream per channel for the capacity of `clip_A.wav` |
| `rs.json` | RS(255,225) codewords of 5 seeded 225-byte messages, each with 5, 15 and 16 byte errors: whether reedsolo decodes it, the decoded message, the number of corrected symbols |
| `clip_A.wav` | unsigned input (44.1 kHz mono PCM16) |
| `clip_A_signed_v1.f64`, `.npy` | `sign(clip_A, sk, "{NIPS_MSG}")`, `Options()`, profile wb: float64 samples before quantization (`.f64` is raw little-endian) |
| `clip_A_signed_v1.wav` | `apcaw sign` output for the same input: clip to [-1, 32767/32768], `round(y * 32768)` half-even, PCM16 |
| `clip_A_signed_legacy.wav` | `apcaw sign --legacy` (`Options.legacy()`: seed 42, 8 phase frames, zeroed tail) |
| `clip_A_signed_v1_mp3.wav` | `clip_A_signed_v1.wav` through `ffmpeg -b:a 128k` MP3 and back to 44.1 kHz mono PCM16, padded / trimmed to the input length |
| `soft_A.json` | for the three signed WAVs: wb phase and magnitude soft values over the full capacity (format §7; 17 significant digits) and the verify result (legacy file: `Options.legacy()`, profile wb) |
| `negatives.json` | the signed file under the wrong key and the unsigned file under the right key: not verified, with the verifier's work counters |

Matching (format §11): integers and bytes exactly; float samples within 1e-9 absolute before
quantization; soft values within 1e-9 absolute. The work counters (`candidates_tried`,
`rs_passes`, `sig_checks`) assume an RS decoder that accepts exactly the words reedsolo accepts
(errors only, t = 15); `rs.json` pins this, including 16-error words. Implementations must also
verify each other's signed WAVs, clean and after the MP3 round trip.

## Attribution

`clip_A.wav` is LibriSpeech test-clean utterance {CLIP_ID} (speaker 8555, chapter 284447,
utterance 0010), cut to 10 s and resampled to 44.1 kHz mono 16-bit PCM for the paper's
experiments. LibriSpeech: V. Panayotov, G. Chen, D. Povey, S. Khudanpur, "Librispeech: an ASR
corpus based on public domain audio books", ICASSP 2015, https://www.openslr.org/12, licensed
CC BY 4.0. The signed and transcoded files are derivatives under the same licence.
"""


# ----------------------------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-mp3", action="store_true")
    args = ap.parse_args()
    VECTORS.mkdir(parents=True, exist_ok=True)
    LOCAL_TMP.mkdir(exist_ok=True)

    sk, pk = keygen(SECRET)
    _, pk_other = keygen(OTHER_SECRET)
    kseed = seed_from_pk(pk)
    seeds = LAYOUT_SEEDS + [kseed]

    vec = {}
    vec["layout"] = {
        "description": "Kp = phase_bins(seed), pairs[perm] = mag_pairs(seed); format §2",
        "seeds": [{"seed": s, **{p.name: {"phase_bins": phase_bins(s, p).tolist(),
                                          "mag_pairs": mag_pairs(s, p).tolist()} for p in (WB, NB)}}
                  for s in seeds]}
    mt = []
    for s in seeds:
        out = mt19937_outputs(s, 16)
        assert out == np.random.RandomState(s).randint(0, 2**32, size=16, dtype=np.uint64).tolist()
        mt.append({"seed": s, "outputs": out})
    vec["mt19937"] = {"description": "first 16 raw uint32 outputs of MT19937 init_genrand(seed) "
                                     "= numpy.random.RandomState(seed)", "seeds": mt}

    # -- payloads and streams --------------------------------------------------------------------
    x, sr = read_audio(CLIP_SRC)
    assert sr == SR
    cap = capacity(len(x), WB)
    msgs = []
    for m in ("", "A", NIPS_MSG, LONG_MSG):
        mb = m.encode()
        p = build_payload(mb, sk)
        nb = 8 * len(p)
        ent = {"message_hex": mb.hex(), "message_len": len(mb), "signature_hex": p[2 + len(mb):-30].hex(),
               "payload_hex": p.hex(), "payload_bits": nb,
               "header_bits": bits_str(np.unpackbits(np.frombuffer(nb.to_bytes(4, "big"), np.uint8))),
               "streams_clip_A_wb": {}}
        for ch, c, rmax in (("phase", cap.cap_phase, WB.rp), ("magnitude", cap.cap_mag, WB.rm)):
            s = build_stream(p, c, rmax)
            ent["streams_clip_A_wb"][ch] = {
                "capacity": c, "replicas": replicas(c, nb, rmax), "stream_len": len(s),
                "stream_hex": np.packbits(s).tobytes().hex()}
        msgs.append(ent)
    vec["payload"] = {
        "description": "payload C = RS(30)(be16(len) || M || S), S = Ed25519(sk, M); stream = "
                       "h h h || b^r (format §4–5); stream_hex packs the stream MSB first, "
                       "zero-padded to whole bytes",
        "secret_seed_hex": SECRET.hex(), "public_key_hex": pk.hex(), "key_seed": kseed,
        "clip_A_capacity_wb": {"samples": len(x), "frames": cap.frames, "groups": cap.groups,
                               "phase": cap.cap_phase, "magnitude": cap.cap_mag},
        "messages": msgs}

    # -- Reed-Solomon ---------------------------------------------------------------------------
    from reedsolo import RSCodec, ReedSolomonError
    rsc = RSCodec(30)
    cases = []
    for s in RS_SEEDS:
        rng = np.random.RandomState(s)
        msg = rng.randint(0, 256, size=225).astype(np.uint8).tobytes()
        cw = bytes(rsc.encode(msg))
        corr = []
        for ne in RS_ERRORS:
            pos = sorted(int(i) for i in rng.choice(255, ne, replace=False))
            bad = bytearray(cw)
            for i in pos:
                bad[i] ^= int(rng.randint(1, 256))
            try:
                dm, _, errata = rsc.decode(bytes(bad))
                got = (True, bytes(dm).hex(), len(errata))
            except ReedSolomonError:
                got = (False, None, None)
            d = rs_decode(bytes(bad))
            assert got == ((False, None, None) if d is None else (True, d[0].hex(), d[1]))
            corr.append({"n_errors": ne, "positions": pos, "received_hex": bytes(bad).hex(),
                         "decodes": got[0], "decoded_hex": got[1], "n_corrected": got[2]})
        cases.append({"seed": s, "message_hex": msg.hex(), "codeword_hex": cw.hex(), "corrupted": corr})
    vec["rs"] = {"description": "reedsolo RSCodec(30) over GF(2^8) (prim 0x11d, generator 2, "
                                "fcr 0); each error XORs a nonzero byte at the listed position",
                 "cases": cases}

    for name in ("layout", "mt19937", "payload", "rs"):
        dump(VECTORS / f"{name}.json", vec[name])
    dump(SELFTEST_JSON, selftest.build(vec))

    # -- audio ----------------------------------------------------------------------------------
    shutil.copyfile(CLIP_SRC, VECTORS / "clip_A.wav")
    y = sign(x, SR, sk, NIPS_MSG)
    y.astype("<f8").tofile(VECTORS / "clip_A_signed_v1.f64")
    np.save(VECTORS / "clip_A_signed_v1.npy", y)
    cli_sign(VECTORS / "clip_A.wav", VECTORS / "clip_A_signed_v1.wav", legacy=False)
    w, _ = read_audio(VECTORS / "clip_A_signed_v1.wav")
    assert np.array_equal(np.round(w * 32768).astype(np.int16), quantize_pcm16(y))
    cli_sign(VECTORS / "clip_A.wav", VECTORS / "clip_A_signed_legacy.wav", legacy=True)
    files = [("clip_A_signed_v1.wav", "v1"), ("clip_A_signed_legacy.wav", "legacy")]
    if not args.no_mp3:
        mp3_roundtrip(VECTORS / "clip_A_signed_v1.wav", VECTORS / "clip_A_signed_v1_mp3.wav", len(x))
        files.insert(1, ("clip_A_signed_v1_mp3.wav", "v1"))
    print("wrote clip_A.wav, clip_A_signed_v1.{f64,npy,wav}, " + ", ".join(f for f, _ in files[1:]))

    parts = []
    for name, opt in files:
        o = Options.legacy() if opt == "legacy" else Options()
        a, _ = read_audio(VECTORS / name)
        ps, ms = read_soft(a, o.seed if o.seed is not None else kseed, WB, o)
        r = verify(a, SR, pk, WB if opt == "legacy" else None, o)
        head = json.dumps({"file": name, "options": opt, "profile": "wb", "verify": result_fields(r)})
        parts.append(head[:-1] + f', "phase_soft": {floats17(ps)}, "mag_soft": {floats17(ms)}}}')
        print(f"  {name}: verified={r.verified} channel={r.channel} path={r.path} "
              f"rs_corrected={r.rs_corrected}")
    desc = ("wb soft values of format §7 over the full capacity (17 significant digits) and the "
            "verify result; options 'v1' = Options() with the key seed and profile auto, "
            "'legacy' = Options.legacy() (seed 42, erasure_tau 0, header verifier) with profile wb")
    (VECTORS / "soft_A.json").write_text(
        "{" + f'"description": {json.dumps(desc)}, "public_key_hex": "{pk.hex()}", "files": [\n'
        + ",\n".join(parts) + "\n]}\n")
    json.loads((VECTORS / "soft_A.json").read_text())
    print("wrote vectors/soft_A.json")

    neg = []
    for name, key, what in (("clip_A_signed_v1.wav", pk_other, "wrong key"),
                            ("clip_A.wav", pk, "unsigned audio")):
        a, _ = read_audio(VECTORS / name)
        r = verify(a, SR, key)
        assert not r.verified
        neg.append({"file": name, "case": what, "public_key_hex": key.hex(), **result_fields(r)})
        print(f"  negative {what}: {r.candidates_tried} tried, {r.rs_passes} RS passes, "
              f"{r.sig_checks} signature checks")
    dump(VECTORS / "negatives.json", {
        "description": "must not verify; counters of the v1 verifier (profile auto: wb then nb, "
                       "global de-duplication of candidate byte strings)",
        "cases": neg})

    (VECTORS / "README.md").write_text(README)
    print("wrote vectors/README.md")

    # -- manifest -------------------------------------------------------------------------------
    import cryptography
    from importlib.metadata import version
    names = sorted(p.name for p in VECTORS.iterdir() if p.is_file() and p.name != "MANIFEST.json")
    dump(VECTORS / "MANIFEST.json", {
        "format": "apcaw-v1 conformance vectors",
        "generator": "tools/make_vectors.py",
        "clip_A_source": f"LibriSpeech test-clean {CLIP_ID} (Panayotov et al. 2015, CC BY 4.0)",
        "apcaw": apcaw.__version__, "python": platform.python_version(), "numpy": np.__version__,
        "reedsolo": version("reedsolo"), "cryptography": cryptography.__version__,
        "ffmpeg": None if args.no_mp3 else ffmpeg_version(),
        "files": {n: {"sha256": hashlib.sha256((VECTORS / n).read_bytes()).hexdigest(),
                      "bytes": (VECTORS / n).stat().st_size} for n in names}})
    return 0


if __name__ == "__main__":
    sys.exit(main())
